Fixed error when call function disable/enable control button before initializing the control
geoman-io/leaflet-geoman pull request #1143
Opened 2022-04-21 19:33 UTC by vvlladd28

Fixed #1141

2022-04-21 19:34 UTC, vvlladd28 commented
Please review my PR @Falke-Design

2022-04-21 19:43 UTC, Falke-Design commented
Can you please add a test?

2022-04-21 19:47 UTC, vvlladd28 commented
Can you tell me how to write a test correctly because all tests are called after initializing control?

2022-04-21 19:49 UTC, Falke-Design commented
Look into this [test](https://github.com/geoman-io/leaflet-geoman/blob/9297f87f29c98978fb6f70980b7327bfa3098202/cypress/integration/circle.spec.js#L187). First remove the existing map, then create a new map as [here](https://github.com/geoman-io/leaflet-geoman/blob/9297f87f29c98978fb6f70980b7327bfa3098202/cypress/support/index.js#L37)

2022-04-21 20:05 UTC, vvlladd28 commented
Thanks for the help in write test

2022-04-21 20:15 UTC, Falke-Design requested changes

2022-04-21 20:15 UTC, Falke-Design commented on cypress/integration/toolbar.spec.js
> +      );
```suggestion
```

tiles are not necessary

2022-04-21 20:15 UTC, Falke-Design commented on cypress/integration/toolbar.spec.js
> +      cy.window.map = map;
```suggestion
```
we don't want to overwrite the global map object

2022-04-24 17:51 UTC, Falke-Design approved these changes

2022-05-20 13:55 UTC, merged