Additional Custom Control Methods
geoman-io/leaflet-geoman pull request #1295
Opened 2023-01-19 04:11 UTC by TurtIeSocks

Motivation is for React reasons, since an error is thrown if a button has already been mounted (when the component rerenders...), these checks are helpful to avoid issues.

- adds `buttonExists(name: string)` to get the status of a button
- adds `getCustomButtons()` that returns an object of all of the custom controls
- ts definitions

2023-02-19 10:38 UTC, Falke-Design requested changes
Please check my review. 

If you want, it would be helpful to have following methods too:
- L.Controls: `disabled() {return  !!this._button.disabled}`
- L.Controls: `visible(){return !!this._map}`
- L.Controls: `getButtonsOptions() {return this._button}`

2023-02-19 10:38 UTC, Falke-Design commented on src/js/Toolbar/L.PM.Toolbar.js
> +  },
Let us make this more general:

```suggestion
getButtonsInBlock(name) {
  const buttonsInBlock = {};
    if(name){
    for(const buttonName in map.pm.Toolbar.getButtons()){
      const button = map.pm.Toolbar.getButtons()[buttonName];
      // draw controls doesn't have a block
      if(button._button.tool === name || (name === 'draw' && !button._button.tool)){
        buttonsInBlock[buttonName] = button;
      }
    }
  }
  return buttonsInBlock;
}
```

2023-02-19 10:38 UTC, Falke-Design commented on src/js/Toolbar/L.PM.Toolbar.js
> +  },
Would it be ok for you to implementend `getButton(name)`? It returns `undefined` if it doesn't exists.

2023-02-19 10:38 UTC, Falke-Design commented on README.md
> +| getButtons() | `Object`       | Get an object of the current buttons button.
👍

2023-02-19 14:08 UTC, Falke-Design requested changes
And please add tests for the new methods

2024-02-24 18:33 UTC, TurtIeSocks commented
Apologies for the delay @Falke-Design, finally came back to this and fixed suggestions.

2024-02-27 21:38 UTC, Falke-Design requested changes

2024-02-27 21:38 UTC, Falke-Design commented on src/js/Toolbar/L.PM.Toolbar.js
> +    return Boolean(this.getButtons()[name]);
let us change this to:
```suggestion
    return Boolean(this.getButton(name));
```

2024-02-27 21:38 UTC, Falke-Design commented on src/js/Toolbar/L.PM.Toolbar.js
> +        const button = this.getButtons()[buttonName];
```suggestion
        const button = this.getButton(buttonName);
```

2024-02-27 21:40 UTC, Falke-Design commented on src/js/Toolbar/L.PM.Toolbar.js
> +        const button = this.getButton(buttonName);
```suggestion
        const button = this.getButtons()[buttonName];
```

2024-02-27 21:47 UTC, merged

2024-02-27 21:48 UTC, Falke-Design commented
Thank you for your contribution!