fix global keyboard and window listeners are not removed after the map is destroyed
geoman-io/leaflet-geoman pull request #1434
Opened 2024-01-02 16:05 UTC by plainheart

Hi,

I noticed the global listeners bound in the keyboard mixin were not unbound after the map was destroyed, which makes the listener always exist and makes the code throw errors even if the component is destroyed in those single-page applications.

So I think we should unbind the listeners somewhere after destroying the map. I currently put this logic into the `_initKeyListener` function of the `Keyboard` mixin. Also, to keep the isolation of the mixin, I changed the singleton Keyboard mixin object to a function that returns a new object at each call to make it work for multiple map instances, or the entire listener will be removed as long as one map is destroyed, which causes the event listener for other maps to not work.

To reproduce,

- https://codepen.io/plainheart/pen/bGZVxgv
- Or just open `demo/index.html` in this project and call `map.remove()`

2024-01-05 14:32 UTC, Falke-Design requested changes
Thank you, good catch!

I will approve this but are you able to add some tests?

And do you think we have with some other Mixins problems when there are multiple maps?

2024-02-04 11:05 UTC, plainheart commented
@Falke-Design Just added a simple test case but I'm not sure if it's enough.

> And do you think we have with some other Mixins problems when there are multiple maps?

It looks other mixins are not binding events on the global objects like `window` and `document`. There might be no problem with them. One suggestion is to provide an API to allow users to unmount (or destroy/remove/dispose) the PM plugin and clean up the relative resources like listeners and mounted objects.

2024-02-04 15:30 UTC, Falke-Design requested changes
This test is enough for now. Please check out the comments

2024-02-04 15:30 UTC, Falke-Design commented on src/js/Mixins/Keyboard.js
>    },
I think a named function would be better and cleaner. Also `once` should be enough
```suggestion
    map.once('unload', this_unbindKeyListenerEvents, this);
  },
  _unbindKeyListenerEvents() {
      L.DomEvent.off(document, 'keydown keyup', this._onKeyListener, this);
      L.DomEvent.off(window, 'blur', this._onBlur, this);
  },
```

2024-02-04 15:30 UTC, Falke-Design commented on cypress/integration/mixins.spec.js
> +      const { map, document } = window;
This should be enough:
```suggestion
    cy.window().then(({ map, document }) => {
```

2024-02-04 15:50 UTC, Falke-Design commented on cypress/integration/mixins.spec.js
> +      const { map, document } = window;
Never mind, i didn't see that you need the window object later

2024-02-04 15:51 UTC, Falke-Design approved these changes

2024-02-04 15:57 UTC, Falke-Design requested changes

2024-02-04 15:57 UTC, Falke-Design commented on cypress/integration/mixins.spec.js
> +  it('KeyboardMixin', () => {
```suggestion
describe('', (KeyboardMixin) => {
  it('Should unbind event listeners that bound by the KeyboardMixin after the map is destroyed', () => {
```

2024-02-04 15:57 UTC, Falke-Design commented on src/js/Mixins/Keyboard.js
> +    map.once('unload', this_unbindKeyListenerEvents, this);
```suggestion
    map.once('unload', this._unbindKeyListenerEvents, this);
```

2024-02-04 16:02 UTC, Falke-Design commented on cypress/integration/mixins.spec.js
> +  it('KeyboardMixin', () => {
Sorry, I have copied to the wrong position

2024-02-04 16:02 UTC, Falke-Design commented on cypress/integration/mixins.spec.js
> +describe('', (KeyboardMixin) => {
```suggestion
describe('KeyboardMixin', () => {
```

2024-02-04 16:09 UTC, Falke-Design approved these changes
Thank you for your contribution!

2024-02-04 16:10 UTC, merged