fixes setLang to handle navigator.language formats (such as "fr-FR")
geoman-io/leaflet-geoman pull request #1499
Opened 2024-06-13 08:59 UTC by mscno

2024-06-13 15:48 UTC, Falke-Design requested changes

2024-06-13 15:48 UTC, Falke-Design commented on src/assets/translations/index.js
> +  pt,
we should add this in the typescript file too

2024-06-14 08:42 UTC, mscno reviewed
great!

2024-06-15 11:16 UTC, Falke-Design approved these changes

2024-06-15 11:16 UTC, merged