Undo / Redo History Function
geoman-io/leaflet-geoman pull request #741
Opened 2020-12-29 09:59 UTC by Falke-Design

This feature is under development!

Having lots of tests from different people would be nice

Fix: #320

2021-01-01 10:46 UTC, codeofsumit requested changes
- [ ] Undo Redo Logic sollte komplett gekapselt sein
- [ ] Scopes: Mode, Drawing Mode, Global
- [ ] GlobalReverting should be ModeReverting
- [ ] New GlobalRevert across everything
- [ ] pm:edit/drag/etc -> `createChangeOnLayer`
- [ ] addHistoryEntry, removeHistoryEntry, getHistory
- [ ] Transactions vs Snapshots: Consistency in Applying and Storing
- [ ] Architektur: global History with EVERYTHING (one array), then filter based on 

Kontext

```js
[
  {
    diff: `theChange`,
    layer: `<layerRef>`
    mode: `Removal/Edit/etc`
    action: `Draw/Move/Drag/...`
  }
]
```

2021-12-19 14:40 UTC, t1a2l commented
where does this feature stands?

2021-12-19 19:12 UTC, Falke-Design commented
@t1a2l it is currently on hold because we don't have the time to develop it

2022-05-23 14:02 UTC, winston01 commented
Any chance of this getting merged and published soon?

2024-02-19 14:26 UTC, Preefix commented
Are there any updated on this feature?

2024-05-27 15:44 UTC, sstainba commented
Any update on this feature?

2024-07-17 11:22 UTC, t1a2l commented
@Falke-Design Hey, any ETA on this feature? it is in development since 2020. It is the only feature keeping me from moving from leafelt draw to this plugin.

2024-07-17 16:03 UTC, Falke-Design commented
@t1a2l sorry to hear that but sadly we have this feature currently not on our roadmap.

2025-04-25 19:50 UTC, Falke-Design commented
We have added a `cancel` action to all modes in Geoman Pro. For now, this feature will not be included in the free version, and we will not be adding undo or redo functionality.

https://geoman.io/docs/leaflet/changelog/pro#v2140-adding-cancel-to-modes

2025-04-25 19:50 UTC, closed without merging