add Ukrainian translation
geoman-io/leaflet-geoman pull request #812
Opened 2021-03-10 14:32 UTC by diadenchuk

2021-03-10 14:49 UTC, Falke-Design requested changes
Thanks for adding this language. Please change the order of the languages in the readme.

2021-03-11 09:48 UTC, diadenchuk commented on README.md
> +Currently available languages are `da`, `de`, `el`, `en`, `es`, `fa`, `fr`, `hu`, `id`, `it`, `nl`, `no`, `pl`, `pt_br`, `ro`, `ru`, `sv`, `zh`, `zh_tw` and `ua`.
done ✅

2021-03-11 09:55 UTC, Falke-Design approved these changes

2021-03-22 17:33 UTC, codeofsumit commented
We are closing this one to apply the required changes to the branch and then merge it. Thanks for your work on this @diadenchuk

2021-03-22 17:37 UTC, merged